### ISSUE TITLE
Display standalone actions

### ISSUE THREAD

**Issue by Flavien-Panunzio** [pitchayakit/nova-action-button-selector#9]
I was on version 2.0.1 and all my standalone actions were displayed very well until then, however, since I updated, I no longer have a display of my standalone actions

**Comment by pitchayakit** [comment]
Hi @Flavien-Panunzio 
Thanks for your reporting.
I guess you are in another repository that is not under my maintenance and my latest version is [v1.2.2](https://github.com/pitchayakit/nova-action-button-selector/releases/tag/v1.2.2)

Agree that the standalone actions should be turned into a button as well and I have not done with this feature.
